# Import Modules

In [1]:
from astropy.io.fits import *
from numpy           import *
from pandas          import *

# Load Data

In [2]:
Fits    = open("./xstar.fits")
Pointer = Fits[1].data[0][0]
Real    = Fits[2].data[0][0]
Integer = Fits[3].data[0][0]
String  = Fits[4].data[0][0]

# Electron

In [3]:
Electron = {  1:1 ,
              2:2 ,   3:1 ,
              4:3 ,   5:2 ,   6:1 ,
              7:4 ,   8:3 ,   9:2 ,  10:1 ,
             11:5 ,  12:4 ,  13:3 ,  14:2 ,  15:1 ,
             16:6 ,  17:5 ,  18:4 ,  19:3 ,  20:2 ,  21:1 ,
             22:7 ,  23:6 ,  24:5 ,  25:4 ,  26:3 ,  27:2 ,  28:1 ,
             29:8 ,  30:7 ,  31:6 ,  32:5 ,  33:4 ,  34:3 ,  35:2 ,  36: 1,
             37:9 ,  38:8 ,  39:7 ,  40:6 ,  41:5 ,  42:4 ,  43:3 ,  44: 2,  45: 1,
             46:10,  47:9 ,  48:8 ,  49:7 ,  50:6 ,  51:5 ,  52:4 ,  53: 3,  54: 2,  55: 1,
             56:11,  57:10,  58:9 ,  59:8 ,  60:7 ,  61:6 ,  62:5 ,  63: 4,  64: 3,  65: 2,  66: 1,
             67:12,  68:11,  69:10,  70:9 ,  71:8 ,  72:7 ,  73:6 ,  74: 5,  75: 4,  76: 3,  77: 2,  78: 1,
             79:13,  80:12,  81:11,  82:10,  83:9 ,  84:8 ,  85:7 ,  86: 6,  87: 5,  88: 4,  89: 3,  90: 2,  91: 1,
             92:14,  93:13,  94:12,  95:11,  96:10,  97:9 ,  98:8 ,  99: 7, 100: 6, 101: 5, 102: 4, 103: 3, 104: 2, 105: 1,
            106:15, 107:14, 108:13, 109:12, 110:11, 111:10, 112:9 , 113: 8, 114: 7, 115: 6, 116: 5, 117: 4, 118: 3, 119: 2, 120: 1,
            121:16, 122:15, 123:14, 124:13, 125:12, 126:11, 127:10, 128: 9, 129: 8, 130: 7, 131: 6, 132: 5, 133: 4, 134: 3, 135: 2, 136: 1,
            137:17, 138:16, 139:15, 140:14, 141:13, 142:12, 143:11, 144:10, 145: 9, 146: 8, 147: 7, 148: 6, 149: 5, 150: 4, 151: 3, 152: 2, 153: 1,
            154:18, 155:17, 156:16, 157:15, 158:14, 159:13, 160:12, 161:11, 162:10, 163: 9, 164: 8, 165: 7, 166: 6, 167: 5, 168: 4, 169: 3, 170: 2, 171: 1,
            172:19, 173:18, 174:17, 175:16, 176:15, 177:14, 178:13, 179:12, 180:11, 181:10, 182: 9, 183: 8, 184: 7, 185: 6, 186: 5, 187: 4, 188: 3, 189: 2, 190: 1,
            191:20, 192:19, 193:18, 194:17, 195:16, 196:15, 197:14, 198:13, 199:12, 200:11, 201:10, 202: 9, 203: 8, 204: 7, 205: 6, 206: 5, 207: 4, 208: 3, 209: 2, 210: 1,
            211:21, 212:20, 213:19, 214:18, 215:17, 216:16, 217:15, 218:14, 219:13, 220:12, 221:11, 222:10, 223: 9, 224: 8, 225: 7, 226: 6, 227: 5, 228: 4, 229: 3, 230: 2, 231: 1,
            232:22, 233:21, 234:20, 235:19, 236:18, 237:17, 238:16, 239:15, 240:14, 241:13, 242:12, 243:11, 244:10, 245: 9, 246: 8, 247: 7, 248: 6, 249: 5, 250: 4, 251: 3, 252: 2, 253:1,
            254:23, 255:22, 256:21, 257:20, 258:19, 259:18, 260:17, 261:16, 262:15, 263:14, 264:13, 265:12, 266:11, 267:10, 268: 9, 269: 8, 270: 7, 271: 6, 272: 5, 273: 4, 274: 3, 275:2, 276:1,
            277:24, 278:23, 279:22, 280:21, 281:20, 282:19, 283:18, 284:17, 285:16, 286:15, 287:14, 288:13, 289:12, 290:11, 291:10, 292: 9, 293: 8, 294: 7, 295: 6, 296: 5, 297: 4, 298:3, 299:2, 300:1,
            301:25, 302:24, 303:23, 304:22, 305:21, 306:20, 307:19, 308:18, 309:17, 310:16, 311:15, 312:14, 313:13, 314:12, 315:11, 316:10, 317: 9, 318: 8, 319: 7, 320: 6, 321: 5, 322:4, 323:3, 324:2, 325:1,
            326:26, 327:25, 328:24, 329:23, 330:22, 331:21, 332:20, 333:19, 334:18, 335:17, 336:16, 337:15, 338:14, 339:13, 340:12, 341:11, 342:10, 343: 9, 344: 8, 345: 7, 346: 6, 347:5, 348:4, 349:3, 350:2, 351:1,
            352:27, 353:26, 354:25, 355:24, 356:23, 357:22, 358:21, 359:20, 360:19, 361:18, 362:17, 363:16, 364:15, 365:14, 366:13, 367:12, 368:11, 369:10, 370: 9, 371: 8, 372: 7, 373:6, 374:5, 375:4, 376:3, 377:2, 378:1,
            379:28, 380:27, 381:26, 382:25, 383:24, 384:23, 385:22, 386:21, 387:20, 388:19, 389:18, 390:17, 391:16, 392:15, 393:14, 394:13, 395:12, 396:11, 397:10, 398: 9, 399: 8, 400:7, 401:6, 402:5, 403:4, 404:3, 405:2, 406:1,
            407:29, 408:28, 409:27, 410:26, 411:25, 412:24, 413:23, 414:22, 415:21, 416:20, 417:19, 418:18, 419:17, 420:16, 421:15, 422:14, 423:13, 424:12, 425:11, 426:10, 427: 9, 428:8, 429:7, 430:6, 431:5, 432:4, 433:3, 434:2, 435:1,
            436:30, 437:29, 438:28, 439:27, 440:26, 441:25, 442:24, 443:23, 444:22, 445:21, 446:20, 447:19, 448:18, 449:17, 450:16, 451:15, 452:14, 453:13, 454:12, 455:11, 456:10, 457:9, 458:8, 459:7, 460:6, 461:5, 462:4, 463:3, 464:2, 465:1}

# Level Data

## Load Level Data

In [4]:
Z             = []
Ion           = []
E             = []
Level         = []
N             = []
L             = []
S             = []
J             = []
Energy        = []
Potential     = []
Configuration = []

for n in range(390627):
    if Pointer[10*n+1]==6:
        Z             += [Integer[Pointer[10*n+8]+2]]
        Ion           += [Integer[Pointer[10*n+8]+4]]
        E             += [Electron[Integer[Pointer[10*n+8]+4]]]
        Level         += [Integer[Pointer[10*n+8]+3]]
        N             += [Integer[Pointer[10*n+8]-1]]
        L             += [Integer[Pointer[10*n+8]+1]]
        S             += [Integer[Pointer[10*n+8]+0]]
        J             += [int(Real[Pointer[10*n+7]+0])]
        Energy        += ["{0:.6e}".format(Real[Pointer[10*n+7]-1])]
        Potential     += ["{0:.6e}".format(Real[Pointer[10*n+7]+2])]
        Configuration += ["".join(list(map(chr,String[Pointer[10*n+9]-1:Pointer[10*n+19]-1])))]

df01 = DataFrame(data={"Z":Z, "Ion":Ion, "Electron":E, "Level":Level, "N":N, "L":L, "2S+1":S, "2J+1":J, "Energy":Energy, "Potential":Potential, "Configuration":Configuration})
df01

,Z,Ion,Electron,Level,N,L,2S+1,2J+1,Energy,Potential,Configuration
0,1,1,1,1,1,0,2,2,0.000000e+00,1.360000e+01,1s1.2S_1/2
1,1,1,1,2,2,1,2,2,1.019881e+01,1.360000e+01,1s0.2p1.2P_1/2
2,1,1,1,3,2,1,2,4,1.019873e+01,1.360000e+01,1s0.2p1.2P_3/2
3,1,1,1,4,2,0,2,2,1.019881e+01,1.360000e+01,1s0.2s1.2S_1/2
4,1,1,1,5,3,1,2,2,1.208750e+01,1.360000e+01,1s0.3p1.2P_1/2
...,...,...,...,...,...,...,...,...,...,...,...
17629,30,465,1,29,6,3,2,14,1.204410e+04,1.238820e+04,1s0.6f1.2F
17630,30,465,1,30,6,4,2,18,1.204410e+04,1.238820e+04,1s0.6g1.2G
17631,30,465,1,31,6,5,2,22,1.204410e+04,1.238820e+04,1s0.6h1.2H
17632,30,465,1,32,12,0,2,1,1.230220e+04,1.238820e+04,superlev
17633,30,465,1,33,1,0,1,1,1.238820e+04,1.238820e+04,continuu

## Save Level Data

In [5]:
for n in range(92,106):
    df01.query("Ion=={0:02d}".format(n)).to_csv("./xstar_database/Si/Si{0:02d}_Level.tsv".format(106-n),sep="\t")
for n in range(326,352):
    df01.query("Ion=={0:02d}".format(n)).to_csv("./xstar_database/Fe/Fe{0:02d}_Level.tsv".format(352-n),sep="\t")

# Spectroscopic Level Photoionization

## Load Spectroscopic Level Photoionization

In [ ]:
Z             = []
Initial_Ion   = []
Initial_Level = []
Final_Ion     = []
Final_Level   = []
N             = []
L             = []
J             = []
Energy        = []
Cross         = []

for i in range(390628):
    if Pointer[10*i+1]==49 or Pointer[10*i+1]==53:
        for j in range(Pointer[10*i+4]//2):
            Z             += [Integer[Pointer[10*i+8]+2]]
            Initial_Ion   += [Integer[Pointer[10*i+8]+6]]
            Initial_Level += [Integer[Pointer[10*i+8]+5]]
            Final_Ion     += [Integer[Pointer[10*i+8]+4]]
            Final_Level   += [Integer[Pointer[10*i+8]+3]]
            N             += [Integer[Pointer[10*i+8]-1]]
            L             += [Integer[Pointer[10*i+8]+0]]
            J             += [Integer[Pointer[10*i+8]+1]]
            Energy        += ["{0:.6e}".format(Real[Pointer[10*i+7]+2*j-1])]
            Cross         += ["{0:.6e}".format(Real[Pointer[10*i+7]+2*j+0])]

df02 = DataFrame(data={"Z":Z,"Initial Ion":Initial_Ion,"Initial Level":Initial_Level,"Final Ion":Final_Ion, "Final Level": Final_Level, "N": N, "L": L, "2J": J, "Energy (Ry)": Energy, "Cross Section (Mb)": Cross})
df02 = df02.sort_values(["Initial Ion","Initial Level"]).reset_index().drop(columns="index")
df02

# Bound-bound Radiative

## Load Bound-bound Radiative

In [11]:
Z             = []
Ion           = []
Initial_Level = []
Final_Level   = []
Energy        = []
Strength      = []
A_coefficient = []

for n in range(390628):
    if Pointer[10*n+1]==50:
        if Real[Pointer[10*n+7]-1]!=0:
            Z             += [Integer[Pointer[10*n+8]+1]]
            Ion           += [Integer[Pointer[10*n+8]+2]]
            Initial_Level += [Integer[Pointer[10*n+8]+0]]
            Final_Level   += [Integer[Pointer[10*n+8]-1]]
            Energy        += ["{0:.6e}".format(12398/Real[Pointer[10*n+7]-1])]
            Strength      += ["{0:.6e}".format(      Real[Pointer[10*n+7]+0])]
            A_coefficient += ["{0:.6e}".format(      Real[Pointer[10*n+7]+1])]

df03 = DataFrame(data={"Z":Z, "Ion":Ion, "Initial Level":Initial_Level, "Final Level":Final_Level, "Energy (eV)":Energy, "Oscillator Strength":Strength, "A Coefficient":A_coefficient})
df03 = df03.sort_values(["Ion","Initial Level","Final Level"]).reset_index().drop(columns="index")
df03

,Z,Ion,Initial Level,Final Level,Energy (eV),Oscillator Strength,A Coefficient
0,1,1,2,1,1.019846e+01,0.000000e+00,6.265030e+08
1,1,1,3,1,1.019838e+01,0.000000e+00,6.265030e+08
2,1,1,5,1,1.208708e+01,0.000000e+00,1.672560e+08
3,1,1,5,4,1.888619e+00,0.000000e+00,2.244880e+07
4,1,1,6,1,1.208710e+01,0.000000e+00,1.672560e+08
...,...,...,...,...,...,...,...
227945,1,465,30,16,4.210394e+02,0.000000e+00,1.139400e+12
227946,1,465,30,22,1.458263e+02,0.000000e+00,9.177200e+11
227947,1,465,30,23,1.454324e+02,0.000000e+00,9.177200e+11
227948,1,465,31,24,1.454331e+02,0.000000e+00,1.365200e+12
227949,1,465,31,25,1.451975e+02,0.000000e+00,1.365200e+12

## Save Bound-bound Radiative

In [12]:
for n in range(92,106):
    df03.query("Ion=={0:02d}".format(n)).to_csv("./xstar_database/Si/Si{0:02d}_Transition.tsv".format(106-n),sep="\t")

# Superlevel Photoionization

## Load Superlevel Photoionization

In [9]:
Z             = []
Initial_Ion   = []
Initial_Level = []
Final_Ion     = []
Final_Level   = []
N             = []
L             = []
S             = []
Energy        = []
Cross         = []

for i in range(390628):
    if Pointer[10*i+1]==70 or Pointer[10*i+1]==99:
        nd = Integer[Pointer[10*i+8]-1]
        nt = Integer[Pointer[10*i+8]+0]
        nx = Integer[Pointer[10*i+8]+1]

        for j in range(nx):
            Z             += [Integer[Pointer[10*i+8]+5]]
            Initial_Ion   += [Integer[Pointer[10*i+8]+9]]
            Initial_Level += [Integer[Pointer[10*i+8]+8]]
            Final_Ion     += [Integer[Pointer[10*i+8]+7]]
            Final_Level   += [Integer[Pointer[10*i+8]+6]]
            N             += [Integer[Pointer[10*i+8]+2]]
            L             += [Integer[Pointer[10*i+8]+3]]
            S             += [Integer[Pointer[10*i+8]+4]]
            Energy        += ["{0:.6e}".format(Real[Pointer[10*i+7]+nd+nt+nd*nt+2*j-1])]
            Cross         += ["{0:.6e}".format(Real[Pointer[10*i+7]+nd+nt+nd*nt+2*j+0])]

df04 = DataFrame(data={"Z":Z, "Initial_Ion":Initial_Ion, "Initial Level":Initial_Level, "Final_Ion":Final_Ion, "Final Level":Final_Level, "N":N, "L":L, "2S+1":S, "Energy (Ry)":Energy, "Cross Section (Mb)":Cross})
df04 = df04.sort_values(["Initial_Ion", "Initial Level", "Final Level"]).reset_index().drop(columns="index")
df04

,Z,Initial_Ion,Initial Level,Final_Ion,Final Level,N,L,2S+1,Energy (Ry),Cross Section (Mb)
0,1,1,32,0,1,12,0,2,0.000000e+00,1.842000e+02
1,1,1,32,0,1,12,0,2,1.142910e-03,1.328000e+02
2,1,1,32,0,1,12,0,2,2.464230e-03,9.586000e+01
3,1,1,32,0,1,12,0,2,4.001510e-03,6.915000e+01
4,1,1,32,0,1,12,0,2,5.789890e-03,4.986000e+01
...,...,...,...,...,...,...,...,...,...,...
21206,1,465,32,0,1,12,0,2,8.307690e+03,5.776980e-09
21207,1,465,32,0,1,12,0,2,9.283480e+03,4.110730e-09
21208,1,465,32,0,1,12,0,2,1.037380e+04,2.919770e-09
21209,1,465,32,0,1,12,0,2,1.159210e+04,2.069090e-09
21210,1,465,32,0,1,12,0,2,1.167050e+04,2.025180e-09

## Save Superlevel Photoionization

In [10]:
for n in range(92,106):
    df04.query("Final_Ion=={0:02d}".format(n)).to_csv("./xstar_database/Si/Si{0:02d}_Superlevel_Photoionization.tsv".format(106-n),sep="\t")

# Superlevel Recombination

## Load Superlevel Recombination

In [32]:
Z             = []
Initial_Ion   = []
Initial_Level = []
Final_Ion     = []
Final_Level   = []
N             = []
L             = []
S             = []
Temperature   = []
Rate          = []

for i in range(390628):
    if Pointer[10*i+1]==70:
        nd = Integer[Pointer[10*i+8]-1]
        nt = Integer[Pointer[10*i+8]+0]
        nx = Integer[Pointer[10*i+8]+1]
        
        for j in range(nt):
            Z             += [Integer[Pointer[10*i+8]+5]]
            Initial_Ion   += [Integer[Pointer[10*i+8]+7]]
            Initial_Level += [Integer[Pointer[10*i+8]+6]]
            Final_Ion     += [Integer[Pointer[10*i+8]+9]]
            Final_Level   += [Integer[Pointer[10*i+8]+8]]
            N             += [Integer[Pointer[10*i+8]+2]]
            L             += [Integer[Pointer[10*i+8]+3]]
            S             += [Integer[Pointer[10*i+8]+4]]
            Temperature   += ["{0:.6e}".format(8.61734*10**(-5)*10**(Real[Pointer[10*i+7]+nd+j-1]))]
            Rate          += ["{0:.6e}".format(                 10**(Real[Pointer[10*i+7]+nd+nt+j-1]))]

df05 = DataFrame(data={"Z":Z, "Initial_Ion":Initial_Ion, "Initial Level":Initial_Level, "Final_Ion":Final_Ion, "Final Level":Final_Level, "N":N, "L":L, "2S+1":S, "Temperature (eV)":Temperature, "Rate":Rate})
df05 = df05.sort_values(["Z", "Initial_Ion", "Initial Level", "Final_Ion"]).reset_index().drop(columns="index")
df05.query("Final_Ion==105")[:20]

,Z,Initial_Ion,Initial Level,Final_Ion,Final Level,N,L,2S+1,Temperature (eV),Rate
6042,14,0,1,105,32,12,0,2,8.617340e-02,4.442221e-10
6043,14,0,1,105,32,12,0,2,1.689170e+01,9.484190e-12
6044,14,0,1,105,32,12,0,2,1.689170e+02,1.042317e-12
6045,14,0,1,105,32,12,0,2,1.689170e+03,6.807696e-14
6046,14,0,1,105,32,12,0,2,8.617340e+03,7.447315e-15

## Save Superlevel Recombination

In [33]:
for n in range(92,106):
    df05.query("Final_Ion=={0:02d}".format(n)).to_csv("./xstar_database/Si/Si{0:02d}_Superlevel_Recombination.tsv".format(106-n), sep="\t")

# Superlevel-bound Radiative

## Define Superlevel-bound Radiative

In [ ]:
Z = []
Ion = []
Initial_Level = []
Final_Level = []
Wavelength = []
Density = []
Temperature = []
A_coefficient = []

for i in range(390628):
    if Pointer[10*i+1]==71:
        nd = Integer[Pointer[10*i+8]-1]
        nt = Integer[Pointer[10*i+8]+0]

        for j in range(nt):
            for k in range(nd):
                Z.append(Integer[Pointer[10*i+8]+3])
                Ion.append(Integer[Pointer[10*i+8]+4])
                Initial_Level.append(Integer[Pointer[10*i+8]+2])
                Final_Level.append(Integer[Pointer[10*i+8]+1])
                Wavelength.append("{0:.6e}".format(Real[Pointer[10*i+7]+nd+nt+nd*nt-1]))
                Density.append("{0:.6e}".format(Real[Pointer[10*i+7]+k-1]))
                Temperature.append("{0:.6e}".format(Real[Pointer[10*i+7]+nd+j-1]))
                A_coefficient.append("{0:.6e}".format(Real[Pointer[10*i+7]+nd+nt+(j+1)*(k+1)-2]))

df06 = DataFrame(data={"Z": Z, "Ion": Ion, "Initial Level": Initial_Level, "Final Level": Final_Level, "Wavelength (A)": Wavelength, "Density": Density, "Temperature": Temperature, "Einstein A Coefficient": A_coefficient})

## Sort Superlevel-bound Radiative

In [ ]:
dfs06 = df06.sort_values(["Ion", "Initial Level", "Final Level"])
dfs06 = dfs06.reset_index()
dfs06 = dfs06.drop(columns="index")
dfs06

        Z  Ion  ...   Temperature  Einstein A Coefficient
0       1    1  ...  3.000000e+00            2.586080e+00
1       1    1  ...  3.000000e+00            3.322080e+00
2       1    1  ...  3.000000e+00            3.869590e+00
3       1    1  ...  3.000000e+00            2.549620e+00
4       1    1  ...  3.000000e+00            3.284990e+00
...    ..  ...  ...           ...                     ...
130850  1  465  ...  5.000000e+00            9.814580e+00
130851  1  465  ...  5.000000e+00            1.010820e+01
130852  1  465  ...  5.000000e+00            1.030990e+01
130853  1  465  ...  5.000000e+00            1.026120e+01
130854  1  465  ...  5.000000e+00            9.291770e+00

[130855 rows x 8 columns]

## Preserve Superlevel-bound Radiative

In [ ]:
dfs06.to_csv("/content/drive/MyDrive/Monaco/Database/Superlevel-bound_Radiative.tsv", sep="\t")

# Autoionization Rates

## Define Autoionization Rates

In [ ]:
Z = []
Ion = []
Initial_Level = []
Final_Level = []
L = []
S = []
J = []
Energy = []
Rate = []
Configuration = []

for n in range(390628):
    if Pointer[10*n+1]==72:
        Z.append(Integer[Pointer[10*n+8]+3])
        Ion.append(Integer[Pointer[10*n+8]+4])
        Initial_Level.append(Integer[Pointer[10*n+8]+1])
        Final_Level.append(Integer[Pointer[10*n+8]+2])
        L.append(Integer[Pointer[10*n+8]+0])
        S.append(Integer[Pointer[10*n+8]-1])
        J.append(int(Real[Pointer[10*n+7]+1]))
        Rate.append("{0:.6e}".format(Real[Pointer[10*n+7]-1]))
        Energy.append("{0:.6e}".format(Real[Pointer[10*n+7]+0]))
        Configuration.append("".join(list(map(chr, String[Pointer[10*n+9]-1:Pointer[10*n+19]-1]))))

df07 = DataFrame(data={"Z": Z, "Ion": Ion, "Initial Level": Initial_Level, "Final Level": Final_Level, "L": L, "2S+1": S, "2J+1": J, "Energy": Energy, "Rate": Rate, "Configuration": Configuration})
df07

     Z  Ion  Initial Level  ...        Energy          Rate  Configuration
0    6   20             50  ...  2.637240e+02  3.470000e+14       2s.2s.1S
1    6   20             51  ...  2.731400e+02  2.020000e+14       2s.2p.1P
2    6   20             52  ...  2.653970e+02  1.350000e+13       2s.2p.3P
3    6   20             53  ...  2.777020e+02  1.430000e+13       2p.2p.1S
4    6   20             54  ...  2.723660e+02  3.730000e+14       2p.2p.1D
..  ..  ...            ...  ...           ...           ...            ...
58  26  350             45  ...  4.732000e+03  1.950000e+14       2s.2p.1P
59  26  350             46  ...  4.683670e+03  1.590000e+13       2s.2p.3P
60  26  350             47  ...  4.766970e+03  3.880000e+13       2p.2p.1S
61  26  350             48  ...  4.728300e+03  2.520000e+14       2p.2p.1D
62  26  350             49  ...  4.711630e+03  6.760000e+13       2p.2p.3P

[63 rows x 10 columns]

## Preserve Autoionization Rate

In [ ]:
for n in range(92,106):
    df07.query("Ion=={0:02d}".format(n)).to_csv("/content/drive/MyDrive/Monaco/Database/Si{0:02d}_Autoionization.tsv".format(106-n), sep="\t")